1620488510202 [Opening serial port: /dev/ttyTHS1.] 
1620488510506 [The robot is connected to ] [/dev/ttyTHS1] 
1620488510507 [Initial robot's topic...] 
1620488512657 [Data from: [w]] 
1620488512658 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 106, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488513281 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x a 0 \ x 0 f \ x 0 0 \ x a 0 \ x 0 f \ x 0 0 \ x 0 3 \ x a 9 \ n \ r ' ) ]] 
1620488513281 [Data from: [w]] 
1620488513281 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 106, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488513648 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x a 0 \ x 0 f \ x 0 0 \ x a 0 \ x 0 f \ x 0 0 \ x 0 3 \ x a 9 \ n \ r ' ) ]] 
1620488513648 [Data from: [w]] 
1620488513648 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 106, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488514793 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x a 0 \ x 0 f \ x 0 0 \ x a 0 \ x 0 f \ x 0 0 \ x 0 3 \ x a 9 \ n \ r ' ) ]] 
1620488514793 [Data from: [s]] 
1620488514793 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 145, in set_stop
    self.write_command(self.command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488515210 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 5 \ x 0 2 N \ n \ r ' ) ]] 
1620488515210 [Data from: [s]] 
1620488515210 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 145, in set_stop
    self.write_command(self.command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488515430 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 5 \ x 0 2 N \ n \ r ' ) ]] 
1620488515430 [Data from: [s]] 
1620488515431 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 99, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 145, in set_stop
    self.write_command(self.command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488516151 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 5 \ x 0 2 N \ n \ r ' ) ]] 
1620488516151 [Data from: [r]] 
1620488516302 [Data from: [r]] 
1620488518629 [Data from: [r]] 
1620488518799 [Data from: [r]] 
1620488519677 [Data from: [w]] 
1620488519677 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 106, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488520296 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x d 0 \ x 0 7 \ x 0 0 \ x d 0 \ x 0 7 \ x 0 0 \ x 0 3 \ x f 9 \ n \ r ' ) ]] 
1620488520296 [Data from: [w]] 
1620488520297 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 106, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1620488520449 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x d 0 \ x 0 7 \ x 0 0 \ x d 0 \ x 0 7 \ x 0 0 \ x 0 3 \ x f 9 \ n \ r ' ) ]] 
1620488520449 [Data from: [w]] 
1620488520449 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 106, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
