1621046149589 [Opening serial port: /dev/ttyTHS1.] 
1621046149900 [The robot is connected to ] [/dev/ttyTHS1] 
1621046149900 [Initial robot's topic...] 
1621046165655 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 116, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 291, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1621046166115 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x d 0 \ x 0 7 \ x 0 0 \ x d 0 \ x 0 7 \ x 0 0 \ x 0 3 \ x f 9 \ n \ r ' ) ]] 
1621046166115 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 109, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 197, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 145, in set_stop
    self.write_command(self.command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1621046167641 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 5 \ x 0 2 N \ n \ r ' ) ]] 
1621046167641 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 116, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 291, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1621046167938 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x d 0 \ x 0 7 \ x 0 0 \ x d 0 \ x 0 7 \ x 0 0 \ x 0 3 \ x f 9 \ n \ r ' ) ]] 
1621046167938 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 109, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 197, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 145, in set_stop
    self.write_command(self.command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1621046168485 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 5 \ x 0 2 N \ n \ r ' ) ]] 
1621046168485 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 123, in handle_command
    self.set_speed([-self._current_speed, -self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 291, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 140, in set_speed
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
1621046169213 [log_latest_command] [[ b y t e a r r a y ( b ' \ x a a \ x f f \ x a 2 \ x d 0 \ x 0 7 \ x f f \ x d 0 \ x 0 7 \ x f f \ x 0 5 \ x f 7 \ n \ r ' ) ]] 
1621046169213 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 109, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 197, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 145, in set_stop
    self.write_command(self.command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 81, in write_command
    count += 1
UnboundLocalError: local variable 'count' referenced before assignment
] 
