1617987008731 [handle_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Arm_moveit.py", line 93, in handle_command
    self.group.set_position_target([self.target.position.x,self.target.position.y,self.target.position.z])
AttributeError: moveit_handle instance has no attribute 'target'
] 
1617987008748 [Finish initializing arm_moveit] 
1617987018047 [key: %s] [Key.up] 
1617987024520 [key: %s] [Key.enter] 
1617987026604 [Position received] 
1617987027606 [command: %f] [None] 
1617987027606 [No command exists try again] 
1617987028607 [command: %f] [None] 
1617987028607 [No command exists try again] 
1617987029610 [command: %f] [None] 
1617987029610 [No command exists try again] 
1617987030611 [command: %f] [None] 
1617987030611 [No command exists try again] 
1617987031223 [key: %s] [u'p'] 
1617987035634 [key: %s] [Key.ctrl] 
1617987035821 [key: %s] [u'c'] 
1617987039550 [key: %s] [u'e'] 
1617987128853 [key: %s] [Key.esc] 
