1618027815021 [handle_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Arm_moveit.py", line 102, in handle_command
    self.group.set_pose_target(self.target, end_link)
AttributeError: moveit_handle instance has no attribute 'target'
] 
1618027815052 [Finish initializing arm_moveit] 
1618027907225 [Position received] 
1618027908226 [command: %f] [1] 
1618027994822 [Position received] 
1618027995824 [command: %f] [1] 
