1618028324719 [handle_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Arm_moveit.py", line 102, in handle_command
    self.group.set_pose_target(self.target, end_link)
AttributeError: moveit_handle instance has no attribute 'target'
] 
1618028324770 [Finish initializing arm_moveit] 
